version: '3'

services:

  web:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 888:80
    restart: always
    depends_on:
      - php

  php:
    build:
      context: docker/php
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      IRIS_ENV: docker
    depends_on:
      - db
      - redis

  db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_DB=iriscrm
      - POSTGRES_USER=iris
      - POSTGRES_PASSWORD=iris
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    volumes:
      - ./docker/data/redis:/data
